### ISSUE TITLE
Class attributes prefixed with `_`

### ISSUE THREAD

**Issue by cilim** [infinum/rubocop-infinum#6]
On some projects I see that developers use `@_some_class_attribute`, and on some it's without the underscore prefix.

What do you think about creating a cop for this @infinum/backend-team ?

**Comment by d4be4st** [comment]
underscore denounces private class variables. Variables that should not be used directly.

Do not know if you can create a cop like that

**Comment by JureCindro** [comment]
I underscore class variables if the conventional reader method is actually a writer method as ruby does not have method overloading.

```ruby
class << self
  attr_reader :_some_class_attribute

  @_some_class_attribute = 'foo'

  def some_class_attribute(new_value)
    @_some_class_attribute = new_value
  end
end
```

I just thought that this could be circumvented with a guard clause, but only if the attribute is not nullable
```ruby
class << self
  @some_class_attribute = 'foo'

  def some_class_attribute(new_value = nil)
    return @some_class_attribute unless new_value

    @some_class_attribute = new_value
  end
end
```
